# Generated by Django 4.2 on 2023-09-08 18:10

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_deck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimages',
            name='image',
            field=models.FileField(unique=True, upload_to=cards.models.user_based_uploader),
        ),
    ]
